terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }

  # Partial config: the bucket name is generated by the bootstrap step and
  # passed in at init time, so it isn't hardcoded here.
  #   tofu init -backend-config="bucket=$TF_STATE_BUCKET"
  backend "s3" {
    key          = "so-many-dogs/main.tfstate"
    region       = "us-east-2"
    encrypt      = true
    use_lockfile = true
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project   = var.project
      ManagedBy = "opentofu"
    }
  }
}

data "aws_caller_identity" "current" {}
